services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/app
      - postgres_url=postgresql+asyncpg://postgres:123456@postgres:5432/postgres
    command: >
      sh -c "/app/.venv/bin/alembic upgrade head &&
             /app/.venv/bin/uvicorn src.main:app --host 0.0.0.0 --port 8000"