services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app